### ISSUE TITLE
Skills translator skills are lost with linkedin integration?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/veterans-employment-center#108]
When I used this, it removed all of my fake infantryman skills. :(

**Comment by cfeeney-va** [comment]
Importing from linkedin just posts to createresume, so it deletes anything you've entered already (manual info, skills, military history...)  :(

**Comment by cfeeney-va** [comment]
Closed pull request; as discussed current solution will be to put text on the page that warns users to save profile before linkedin import or info will be lost

**Comment by koconnor719** [comment]
low priority; move back to backlog.

**Comment by ayaleloehr** [comment]
Duplicate of #179, which has more details. closing.
