### ISSUE TITLE
discuss Careers and Employment / VEC- Jekyll vs rails division

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/veterans-employment-center#121]
It would be great to keep as much content as possible in the vets.gov jekyll site (markdown), and employment "tools" in rails, but I don't know the best way to do that - as we add more and more strictly content pages into that section. This isn't critical until the content folks are done, but that is likely happening this week or next. 

tagging
@ayaleloehr @plusjeff @akainic 

Would love to discuss more.

**Comment by emilyville** [comment]
After reviewing the IA from the content team, I think there is a fair amount of overlap and some pages will be created in jekyll that will make the pages here redundant, and to be removed. 

Starting a list here (likely any landing page and soleley content page):
https://www.vets.gov/veterans-employment-center/
https://www.vets.gov/veterans-employment-center/for_job_seekers
https://www.vets.gov/veterans-employment-center/employer-resources

Tool based pages like job search, resume builder, skills translator will need to remain. 

We should reprioritize any issues accordingly and not improve pages that are about to be sunset - though none are coming to mind at the moment. 

Tagging 
@dannychapman @akainic  @ayaleloehr @gnakm

**Comment by dannychapman** [comment]
Makes sense to me!

**Comment by plusjeff** [comment]
From a deployment standpoint, we might have to change the URLs for the Rails components of the VEC. Static content might be able to to live at `/veterans-employment-center` URLs, but we'd need `/veterans-employment-center/skills-translator` to go to the Rails application, etc.

**Comment by ayaleloehr** [comment]
@plusjeff agreed. This discussion happened in the #veterans-employment-center slack channel as well, and came to the same conclusion, which is great. Thinking there are around 5-10 URLs that would go to the Rails app, and the rest to the static site.
