### ISSUE TITLE
Resume content consistency

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/veterans-employment-center#123]
The titles and instructions of each section are inconsistent. 
https://www.vets.gov/veterans-employment-center/createresume

There is a spectrum of action to question based titles and some instructions are redundant (e.g. Add The Basics vs. Education & Training). I also think we need to be more consistent with the "Add as many..." categories. If we're going to have an "+Add another" link at the bottom, I wonder if we need to write "add as many" in the instructions at all. There are many design issues on this page as well but I think fixing this first will help the design. 

**Add the basics**
Enter your name

**State Your Objectives**
Enter basic information about your career goals and objectives

**When can you start work?**
When can you start work?

**Your Civilian Skills**
Add your civilian skills. Add as many as necessary by using the autocomplete field

**Education & Training**
Add your education information. Add as many as necessary by using the add education experience link.

**Military Service**
Add your military information. Add as many as necessary by using the add military experience link below.

**Work Experience**
Add your employment information. Add as many as necessary by using the Add work experience link below.

**Volunteer Experience**
Add your work experience. Add as many as necessary by using the Add volunteer experience link.

**Awards**
Enter your award information. Add as many as necessary by using the Add award link.

**Professional Affiliations**
Enter your job title information

**References**
Add your professional references. Add as many as necessary by using the add reference link.

**Location Preference**
Enter your location preferences below. Add as many as necessary by using the Add another location link. (For the best employment search results, specify one or more cities rather than just a state or country.)

**Other**
Enter optional additional information to assist potential employers in finding your profile.

@maryannbrody Good thing I asked you for fresh eyes before. Could you take a look at the other sections?
@rcarthur Could you scan through the resume as well and take a stab at the content?

**Comment by ayaleloehr** [comment]
@gnakm is this better now after the redesign?  If so, please close.

**Comment by gnakm** [comment]
@ayaleloehr yes thanks for pointing this out.
