### ISSUE TITLE
Employer's Profile requirements

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/veterans-employment-center#130]
Currently, companies can make multiple entries (parent company, subsidiary, branches). Ex. We saw two entries for Home Depot and they both had different number for hiring commitments. How do we make sure that companies go in and edit accurate information without conflict or without overriding informations?

**Comment by ayaleloehr** [comment]
The VEC team made the decision that checking for and remediating duplicate commitments should be a manual process, so closing this issue as there is nothing to do on our side currently.
