### ISSUE TITLE
Change Title of "Make Hiring Commitment"

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/veterans-employment-center#133]
During a usability test, a VEC admin said that "Making a Hiring Commitment" makes him assume that he will make an actual hiring commitment when it's really a list of existing commitment entries. The "Stand with Veterans.." description probably fit better under "Your Hiring Commitment Card" https://www.vets.gov/veterans-employment-center/employers
<img width="335" alt="screen shot 2016-02-08 at 11 16 32 am" src="https://cloud.githubusercontent.com/assets/13420618/12891768/08f64a9a-ce57-11e5-8a6b-e7f49e57b32e.png">

Could we change it to "Current Hiring Commitments" and perhaps change the description as well?

**Comment by ayaleloehr** [comment]
Changed to "View all Hiring Commitments"
