### ISSUE TITLE
Search for Employers Default Setting 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/veterans-employment-center#134]
Currently the most recent entries are not showing.
<img width="659" alt="screen shot 2016-02-08 at 2 13 54 pm" src="https://cloud.githubusercontent.com/assets/13420618/12896115/392db40c-ce6e-11e5-8f59-e35ae3dbdefc.png">

It only comes up if you click on the arrows on the date added twice. 
<img width="531" alt="screen shot 2016-02-08 at 2 17 13 pm" src="https://cloud.githubusercontent.com/assets/13420618/12896197/ae7261d6-ce6e-11e5-90d9-64898e081f8e.png">

**Comment by ayaleloehr** [comment]
fixed
