### ISSUE TITLE
Search for Employers Add/Edit Default

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/veterans-employment-center#135]
When you add or edit anything on the search for employers page, it automatically goes back to default opposed to where you left off. https://www.vets.gov/veterans-employment-center/employer-list

**Comment by akainic** [comment]
@gnakm Can you include a screenshot please? Not sure how to recreate this.

**Comment by gnakm** [comment]
@akainic Sorry that was a super vague description with no reference.

So this is very strange it is no longer showing this issue that I was talking about before but I'm seeing another issue. @ayaleloehr Do you remember the default problem we were having before when searching for employees? Was it that it wasn't jumping to the results?

**Comment by gnakm** [comment]
I don't remember if this was the issue or if this a new issue: 

When I go to this page https://www.vets.gov/veterans-employment-center/employer-list (_you have to login in via linkedin or google_) and make changes in an employer's profile (I've been using Marina's to test), it doesn't close go back to the default page but goes to the top of the Employers profile.

<img width="1307" alt="screen shot 2016-02-16 at 11 23 37 am" src="https://cloud.githubusercontent.com/assets/13420618/13082941/d2d8717c-d4a0-11e5-9758-819e6d23b8ff.png">

It makes it seem as if there is an error when the information _is_ updated. 
<img width="816" alt="screen shot 2016-02-16 at 11 27 52 am" src="https://cloud.githubusercontent.com/assets/13420618/13083326/7ec6c8ac-d4a2-11e5-879d-5e10c3a73978.png">

**Comment by akainic** [comment]
Hm, I'm not seeing the bottom screenshot where there are "show", "edit", and "delete" links.

**Comment by gnakm** [comment]
@ayaleloehr Could you give @akainic Employer admin rights?

**Comment by ayaleloehr** [comment]
@gnakm Admin rights given and also figured out steps for setting up admin rights locally. Have passed info to @akainic and will figure out how to document better for others as well.

**Comment by gnakm** [comment]
^ so just for the record, I was trying something out...

I am closing this issue because we made so many iterations after this. This is super outdated.
