### ISSUE TITLE
Increase test coverage to >= 90%

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/veterans-employment-center#136]
The goal of this task to ensure that at least 90% of the lines of code are covered by test coverage.

Accomplishing this involves:

- [ ] Use SimpleCov to measure coverage (Road Runner provides an example)
- [ ] Increase unit test coverage (Rpsec)
- [ ] Increase integration test coverage (Rspec, Capybara)
- [ ] Enable Travis CI builds
- [ ] Enable protected branches (PR merges cannot be completed unless coverage is achieved)

**Comment by ayaleloehr** [comment]
Currently at 72% as of 2/15/2016

**Comment by plusjeff** [comment]
Cool! We'll have to plan how to incrementally increase it over the next few sprints. For example, get it to 80% by the end of this sprint, then get it to 90% the next sprint.

**Comment by cfeeney-va** [comment]
Jeff approved current coverage of 70%
