### ISSUE TITLE
Limit Character Length in Cards

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/veterans-employment-center#139]
Limit Character Length in Cards

This may fix a lot of bugs but the texts are getting cut off in different cards depending on the device. We should limit the character length (to be added to roadrunner).

**Comment by gnakm** [comment]
Related to #186

**Comment by koconnor719** [comment]
moved to backlog

**Comment by gnakm** [comment]
Realted to #157

**Comment by gnakm** [comment]
We no longer have the bug so closing.
