### ISSUE TITLE
Need hover styling on add skills on resume builder

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/veterans-employment-center#142]
No hover styling on adding jobs:
<img width="1057" alt="screenshot 2016-02-12 16 21 23" src="https://cloud.githubusercontent.com/assets/3886085/13020682/cd83f47a-d1a4-11e5-9817-527cd3185267.png">

Mimic hover styles on adding locations:
<img width="1043" alt="screenshot 2016-02-12 16 22 18" src="https://cloud.githubusercontent.com/assets/3886085/13020691/d339e1ae-d1a4-11e5-9ac0-e293afad506d.png">

**Comment by koconnor719** [comment]
blocker: local setup not working
