### ISSUE TITLE
Increase test coverage to 80% this sprint

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#150]

**Comment by koconnor719** [comment]
complete by end of sprint

**Comment by koconnor719** [comment]
@cfeeney-va can you pls. update status on this item.

**Comment by cfeeney-va** [comment]
Test coverage is up to 73.8%.  Having difficulty identifying additional functionality to support; will update.

**Comment by koconnor719** [comment]
74.5 % as of 3/12; christine to talk to jeff if this is good enough--then close it.

**Comment by koconnor719** [comment]
good as is; jeff confirmed.
