### ISSUE TITLE
Follow up w/ Rosye on landing page mockups

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#151]
Gina provided rosye w/ 2 mockups for landing page and job seeker page; need to validate w/ rosye copy is ok or make modifications.

**Comment by gnakm** [comment]
Wed Feb 24 11:30a - 11:45a
Things to show her:

- 2 Mock ups (bring them because she won't have them open)
- Ask about Coursera Logo
- Check in about Usability Videos (have the video uploaded and ready on laptop).

**Comment by koconnor719** [comment]
Sounds good!

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by gnakm** [comment]
Next action item for this is following up with Christi with mockups

**Comment by gnakm** [comment]
Emily did this but I'll take a stab at it.
Primary Green Button = #2e8540
Secondary - Border = #323a45
                     Text = #0071bc 

The button focus for both should be the same one used in the web standards: https://playbook.cio.gov/designstandards/buttons/
