### ISSUE TITLE
mod waffle board

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#152]
delete ready for production; mod staging colums as needed

**Comment by ayaleloehr** [comment]
I started doing this and then realized that it would be awesome to have consistency across projects, so reassigning to @plusjeff.

My current thought is the columns should be:

Backlog. 
Current Sprint. 
In Progress. 
PR created. 
In Staging. 
Done.

**Comment by MarinaMartin** [comment]
The problem we tried to solve with "in staging" and "ready for production" was for items stakeholders need to review in staging and should not move to production until approved. Open to another way to do it but this list seems to go back to missing that distinction.

**Comment by ayaleloehr** [comment]
I believe the current thinking is to have Heroku auto-deploys be used for stakeholder review and PRs not merged into master until stakeholder approval has occurred (this has not yet been implemented). The more I think about this though, I'm not necessarily positive this is a good idea or will work well for larger stakeholder approvals that will be split across multiple PRs.  @plusjeff and I will come up with a solution.

**Comment by plusjeff** [comment]
Definitely agree that the columns need revision, as we haven't really been queueing things up the way we originally expected.

@ayaleloehr I like your list! My only suggestion is to remove the "PR created" column to further simplify it. If PRs are linked to an Issue (via the name, branch name, or the opening comment), then Waffle will tuck them into the original Issue anyway, which will be In Progress.

**Comment by plusjeff** [comment]
After we decide on what we want here, we can change this across the projects. I've been keeping an eye on all the projects, and all are similarly not using the excess columns.

**Comment by emilyville** [comment]
This would be a great agenda item for out sprint planners planning meeting on Thursday! I will add @plusjeff

**Comment by plusjeff** [comment]
Yes indeed!

**Comment by plusjeff** [comment]
We didn't get to this during our Thursday conversation, but will hold a vote in Slack to see if we can change it up.

**Comment by plusjeff** [comment]
Vote is here: https://dsva.slack.com/archives/vetsdotgov/p1456496901000312

**Comment by koconnor719** [comment]
remove ready for staging and ready for production.

**Comment by plusjeff** [comment]
Vote is for removing Ready for Staging and Ready for Production columns.

**Comment by koconnor719** [comment]
alex confirmed done; 3/12
