### ISSUE TITLE
Explorer IE 11 issue w/ feedback forum

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#156]

**Comment by koconnor719** [comment]
get user voice contacts from emily

**Comment by cfeeney-va** [comment]
Was able to replicate this problem in IE11.  Seems to be an issue with IE settings.

Go to Settings->Internet Options->Advanced->Security

If "Use SSL 2.0" is checked, you will have this issue (where you can view vets.gov but not UserVoice).

Uncheck "Use SSL 2.0" and check "Use SSL 3.0" and "Use TLS 1.0" and you should be able to view UserVoice upon page reload (Note: this may have to be done by a system administrator).

Will check in with our contact to see if this solves their problem.

**Comment by cfeeney-va** [comment]
called and emailed contact with fix

**Comment by koconnor719** [comment]
fixed; just need to confirm w/ Paulette.

**Comment by cfeeney-va** [comment]
Update: no response from Paulette

**Comment by koconnor719** [comment]
Pls. resend email one more time and then I think we can just close this.  BUT can you post this info somewhere so the team has it for future reference?  I�m assuming this will come up again, so would be great if the team knew the answer to this.

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by koconnor719** [comment]
closed; christine left 3 messages w/ solution; settings issue.
