### ISSUE TITLE
link in cards (roadrunner)

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#157]

**Comment by gnakm** [comment]
2/25 I'm moving this from current sprint to backlog because 1. This is sort of the next step after content becomes more refined and 2. We're still iterating our ideas for Roadrunner.

**Comment by emilyville** [comment]
Good call. This one turned into a bigger thing ;)

**Comment by ayaleloehr** [comment]
Feels more like a roadrunner thing and not actionable here, so closing.
