### ISSUE TITLE
MOC results bugs

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#171]
user errors reported; pls. retest and mod the skills translator; not sure where these results are coming from? @MarinaMartin 

12B: Homelessness, Wrinkles and Judaism

11C: Street Ministry

68W: Kung Fu

Air Force Missile Specialist: Breast Imaging

**Comment by koconnor719** [comment]
it’s not “issues” so much as it treats all LinkedIn skills the same - so until Veterans are using it
and increasing the importance of relevant skills, the not-relevant skills (such as above) still appear.

**Comment by ayaleloehr** [comment]
Closing because aggregated in #189
