### ISSUE TITLE
Enumerate pages that will still be in Rails app

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#182]
Many pages are moving to vets-website Jekyll site. Which ones are staying in this repo (and we will therefore need specific callouts in the reverse proxies for...)

**Comment by ayaleloehr** [comment]
Staying in this repo:
/search_jobs
/skills-translator
/veterans
/createresume
/users
/employers
/commitments
/favorites
/employer-list
/download_employers
/download_veterans
/download_candidate_veterans

Pages I'm not sure about:
/for_job_seekers

Open questions:
- Is moving back and forth between the static site and app going to cause problems for logged in Veterans or employers?

**Comment by ayaleloehr** [comment]
@gnakm and @emilyville my action from our meeting 2 weeks ago about what pages we should move to the static site was to come up with the routes/pages that will need to stay in the VEC repo. They are above, along with an open question that we will want to make sure we understand before moving pages around.

**Comment by emilyville** [comment]
I'll be in office next week - let's set up a working session to plow through this work. Maybe 2 hours on Thursday or Friday @ayaleloehr ? I think you and I and maybe... @plusjeff ?

**Comment by emilyville** [comment]
@mariana-almeida @rcarthur Please go over and verify this list!
