### ISSUE TITLE
MOC missing or inaccurate

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#188]
This is a collection of prior issues that are all related and I thought should be gathered in one place to fix together.  

Issue #80 - MOC 1110 Navy is currently listed as "Tomahawk Weapon Maintenance Technician" but a tester who was in Navy and was 1110 MOS is telling me that code is Surface Warfare Officer?

Issue #67 - valid MOC codes are not being found when i search Army 15W or Coast Guard 56; are all the MOC codes included in the database?

Issue #78 when searching for older MOC code (e.g., 31K - communications / wire specialist) no results are found. if this is the case for older MOC codes then the tool won't be as useful for older Veterans.

**Comment by ayaleloehr** [comment]
The solution to this may also need to include a way to include MOCs that used to exist but no longer do. Not sure if that is in scope, but feels like it should be.

**Comment by koconnor719** [comment]
alex to give christine info; completion criteria: MOC descriptions are correct.

**Comment by cfeeney-va** [comment]
Update: to do this week

**Comment by koconnor719** [comment]
@cfeeney-va can you pls. post status of where this is at today?

**Comment by cfeeney-va** [comment]
Spreadsheets emailed to Alex are missing some of the example data.  Looking for alternate sources of data; started with Navy codes.  I've already found multiple examples where we've imported two different values for the same code from different sources.  We seem to have used multiple sources for the data and not reconciled any differences.  Additionally, the source I've been looking at doesn't match our data in several places.  If we had one authoritative data source (perhaps from the DoD or a military recruitment facility?) that would be best.

**Comment by koconnor719** [comment]
emailed R.C.  3/9 to ask what the MOC authoritative data source is.

**Comment by ayaleloehr** [comment]
Additional info from the field:

Military Skills translator issues:
o   The following Navy NECs--9502, 8427, 8404, 9505, 8424--do not populate a description in the VEC™ profile/resume builder. Once a user enters an MOS in the Skills Translator and imports respective skills into his/her profile, the description of the MOS will also transfer over. However, none of the above Navy NECs populate a description. 
o   The Air Force MOS, 1C671, populates the wrong description in the VEC™ profile/resume builder. Once a user enters the MOS in the Skills Translator and imports skills into his/her profile, the description does not match the 1C671 duties/responsibilities. 

@cfeeney-va  I don't think there is one authoritative source for this unfortunately.   A few options would include picking the best source we can find and just using it, trying to combine multiple sources, or just manually cleaning up the MOC files we have today.  Use your best judgement on the proper way to proceed.

**Comment by cfeeney-va** [comment]
Did we hear back from R.C.?  A former army contact of mine suggested that military recruitment facilities might be a good place to start for this data, since they would use the codes to enlist people...

**Comment by koconnor719** [comment]
waiting for RC 3/12

**Comment by koconnor719** [comment]
@cfeeney-va pls. post MOC sources here.

**Comment by cfeeney-va** [comment]
current sources:
 goarmy
 mosdb
 O*NET
 Mil2Fed

**Comment by koconnor719** [comment]
mosdb seems good!  too bad it is a .com w/ no info about whose site this is.  i don't think we can use this.

**Comment by cfeeney-va** [comment]
Oh sorry, those are the sources we currently are using (so some of the data in the database is already from mosdb!).  That did seem to be the best one when I was reviewing them...

**Comment by koconnor719** [comment]
compiled spreadsheet of available sources with proposed ones that we use since VEC will not agree to only use ONET; also checking w/ Chris Lynch USDS DoD to see if he knows an authoritative source.

**Comment by cfeeney-va** [comment]
Have downloaded data from the DoD website and imported into my local database.  There are 22367 entries that are updated/validated with the DoD data.  There are still 782 entries that are not from the DoD data, but these are codes that weren't in the DoD files.  My inclination is to leave them for now...thoughts?

Need to validate the import against production data to make sure we don't break anything :)

Updates on individual issues:
o   Issue #80 - MOC 1110 Navy is currently listed as "Tomahawk Weapon Maintenance Technician" but a tester who was in Navy and was 1110 MOS is telling me that code is Surface Warfare Officer?
-DoD data lists this MOC as "TOMAHAWK Weapon System (VLS) Maintenance Technician"

o   Issue #67 - valid MOC codes are not being found when i search Army 15W or Coast Guard 56; are all the MOC codes included in the database?
-both of these codes are included with the import

o   Issue #78 when searching for older MOC code (e.g., 31K - communications / wire specialist) no results are found. if this is the case for older MOC codes then the tool won't be as useful for older Veterans.
-DoD data has two entries for 31k, one active and one inactive:
            Army    | Enlisted | 31K  | DOD_ODB | Combat Signaler     | f
            Army    | Enlisted | 31K  | DOD_ODB | Working Dog Handler | t
I believe the way the current search works, the active one will always show, so we might want to add an option to search for the inactive status

o   The following Navy NECs--9502, 8427, 8404, 9505, 8424--do not populate a description in the VEC™ profile/resume builder. Once a user enters an MOS in the Skills Translator and imports respective skills into his/her profile, the description of the MOS will also transfer over. However, none of the above Navy NECs populate a description. 
-all of these were included with the DoD data and all have descriptions

o   The Air Force MOS, 1C671, populates the wrong description in the VEC™ profile/resume builder. Once a user enters the MOS in the Skills Translator and imports skills into his/her profile, the description does not match the 1C671 duties/responsibilities. 
-entry from DoD data seems good:
   Air Force | Enlisted | 1C671 | Space Systems Operations Craftsman | Manages or performs duties in space operations; space surveillance, space control, missile warning, satellite command and control (C2), or range operations activities.

**Comment by cfeeney-va** [comment]
disclaimer on DoD ODB website:

Standard Mandatory DoD Notice and Consent

You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only.

By using this IS (which includes any device attached to this IS), you consent to the following conditions:

The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations.
At any time, the USG may inspect and seize data stored on this IS.
Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG authorized purpose.
This IS includes security measures (e.g., authentication and access controls) to protect USG interests - not for your personal benefit or privacy.
Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details.
Acknowledgement Of Responsibilities Of Receiving And Maintaining Privacy Act Data

DATA YOU ARE ABOUT TO ACCESS COULD POTENTIALLY BE PROTECTED BY THE PRIVACY ACT OF 1974. You must:

Have completed the necessary training with regards to Security Awareness and safe-guarding Personally Identifiable Information.
Ensure that data is not posted, stored or available in any way for uncontrolled access on any media.
Ensure that data is protected at all times as required by the Privacy Act of 1974 (5 USC 552a(I)(3)) as amended and other applicable DOD regulatory and statutory authority; data will not be shared with offshore contractors; data from the application, or any information derived from the application, shall not be published, disclosed, released, revealed, shown, sold, rented, leased or loaned to anyone outside of the performance of official duties without prior DMDC approval.
Delete or destroy data from downloaded reports upon completion of the requirement for their use on individual projects.
Ensure data will not be used for marketing purposes.
Ensure distribution of data from a DMDC application is restricted to those with a need-to-know. In no case shall data be shared with persons or entities that do not provide documented proof of a need-to-know.
Be aware that criminal penalties under section 1106(a) of the Social Security Act (42 USC 1306(a)), including possible imprisonment, may apply with respect to any disclosure of information in the application(s) that is inconsistent with the terms of application access. The user further acknowledges that criminal penalties under the Privacy Act (5 USC 552a(I)(3)) may apply if it is determined that the user has knowingly and willfully obtained access to the application(s) under false pretenses.
Section 508 of the Rehabilitation Act

The U.S. Department ofDefense is committed to making its electronic and information technologies accessible to individuals with disabilities in accordance with Section 508 of the Rehabilitation Act (29 U.S.C. 794d), as amended in 1999. Send feedback or concerns related to the accessibility of this website to: DoDSection508@osd.mil. For more information about Section 508, please visit the DoD Section 508 website. Last Updated: 08/14/2013.

**Comment by koconnor719** [comment]
christine has to coordinate w/ marina on her task; christine planned to finish by tomorrow; marina can start her task tomorrow.

**Comment by koconnor719** [comment]
Yeah!!!!!!



Sent with Good (www.good.com)


-----Original Message-----
