### ISSUE TITLE
Skills translator issues and inconsistencies

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#189]
The skills translator needs to consistently return more relevant skills (and, most importantly, not return inappropriate skills).  This issue is an aggregate of two other issues that should be resolved together. 

#106 - Copied from issue 1085 in the vets-website repo: The Skills Translator lists the correct job title for USMC MOS 2676 (2676 : Central Asian Cryptologic Linguist), but when you import into the resume builder, the job description is completely wrong. It seems to be the job description for CH-54 helicopters. Perhaps this could reference the VMET database and import job descriptions from there. Or, if it already does that, maybe this particular MOS is buggy. http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11581104-incorrect-job-description

#171 - user errors reported:
12B: Homelessness, Wrinkles and Judaism
11C: Street Ministry
68W: Kung Fu
Air Force Missile Specialist: Breast Imaging

**Comment by koconnor719** [comment]
reassigning to marina to update since she is currently fixing this.

**Comment by koconnor719** [comment]
christine to code review.

**Comment by koconnor719** [comment]
christine to follow up w/ marina.
