### ISSUE TITLE
explorer 9 issue

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#192]
Attached is the screen shot of Employment Center via as viewed from an internally facing GFE laptop with Internet Explorer version 9.0 (https://www.vets.gov/veterans-employment-center/).  
 
![vec pic](https://cloud.githubusercontent.com/assets/13770771/13363311/b3869440-dc96-11e5-9b99-c8036b60f773.png)

**Comment by emilyville** [comment]
Yikes! I'll take a look at this. I thought we fixed this with the css-splitter pr way back when.

**Comment by emilyville** [comment]
ok, verified this is what it looks like in ie9. Will check on the CSS splitter post launch and see if that stopped working or maybe was never implemented in this repo

**Comment by ayaleloehr** [comment]
@emilyville can you verify if this is still happening post launch?

**Comment by emilyville** [comment]
This is way old. I am 90% sure it was sorted and many many other thigns have changed, so closing and please reopen if any new issues arise.

**Comment by koconnor719** [comment]
sounds good!
