### ISSUE TITLE
Make Code Snippet for Post a Job page

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/veterans-employment-center#193]
@mollyblake Following up on our convo. 
https://www.vets.gov/veterans-employment-center/how-to-post-jobs

The schema.org JSON-LD JobPosting Elements Section
Possibility -- Turn it into a table

A schema.org JSON-LD Example Section
Possibility -- Collapse and Hide option for code with Title and description above it https://playbook.cio.gov/designstandards/visual-style/

**Comment by mollyblake** [comment]
Thanks @gnakm appreciate your help with this!

**Comment by gnakm** [comment]
@emilyville Please put the snippet in a grey box :)

**Comment by emilyville** [comment]
This page is on the new site, so suggesting we make the improvement there as a prelaunch task:

https://vets-website-pr-1304.herokuapp.com/employment/employers/post-a-job/

Closing this one, it's now over there: https://github.com/department-of-veterans-affairs/vets-website/issues/1377
