### ISSUE TITLE
Are rake tasks running on AWS?

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/veterans-employment-center#199]
Just checking, I'm not sure how to tell.

**Comment by ayaleloehr** [comment]
Talked to @MarinaMartin to better understand this. 

There is a rake task [here](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/lib/tasks/scheduler.rake) that should be run on a regular schedule. This is not currently occurring on AWS and needs to be set up.

**Comment by ayaleloehr** [comment]
Done!
