### ISSUE TITLE
user voice browser

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#204]
jeff to follow up w/ user voice Explorer issues can't access user voice

**Comment by plusjeff** [comment]
See issue #156

**Comment by plusjeff** [comment]
Will notify User Voice that this occurs for users. Reached out to EmDash to get a contact.

**Comment by koconnor719** [comment]
kelly to follow up w/ jeff on status

**Comment by plusjeff** [comment]
I have not made progress on this, aside from getting contacts from @emilyville :

- "Andrew Moyer" <andrew@uservoice.com>
- "Danny Bloomfield" <danny@uservoice.com>
- "Tyson Beamer" <tyson.beamer@uservoice.com>

**Comment by plusjeff** [comment]
Looking at #156, looks like @cfeeney-va has e-mailed them a bunch already, so not sure there is anything additional to do. Will close this @koconnor719 , but feel free to re-open and I'll reach out to the contacts identified.
