### ISSUE TITLE
Combine or eliminate double header when you login

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/veterans-employment-center#211]
There are two headers here when you log in as an employer using Google. These should be combined or one should be eliminated and the information should be surfaced some other way.

![image](https://cloud.githubusercontent.com/assets/6335546/13572800/2e77c182-e44a-11e5-8cbe-66838d32316c.png)

**Comment by ayaleloehr** [comment]
This is done. @cfeeney-va changed where the "sign out" header went to take care of this.
