### ISSUE TITLE
Veteran Badge

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#238]
prelim requirements: veteran "badge" needs to have reciprocity (not just LinkedIn--need Monster, Career Builder, etc.)

**Comment by MarinaMartin** [comment]
The underlying tech is the same. The business will have to arrange those partnerships with other career portals. LinkedIn has this functionality already; unsure whether the others do.

**Comment by koconnor719** [comment]
closing; old and julie now doing.
