### ISSUE TITLE
Add verified employer

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#242]
add mariana as an employer; mariana can do this w/ her own google or linkedin acccount; if a "verified" account is needed kelly can contact John Thompson and ask that you be verified as a test employer user:)

**Comment by ayaleloehr** [comment]
@mariana-almeida should just be able to log in as an employer via LinkedIn or Google.  If you have any trouble please let me know. And if it works, please close this issue!  :)

**Comment by mariana-almeida** [comment]
I figured it out. Thanks, everyone!
