### ISSUE TITLE
Skills Translator - changed Tips text

### ISSUE THREAD

**Issue by mariana-almeida** [department-of-veterans-affairs/veterans-employment-center#244]
1) For the Skill Translator page, some text changes. These were reviewed by Molly, and written by me. [Uploading 08Jobs_SkillsTranslator_20160328MB.docx…]()

2) Proposed design changes to the tool itself are in review by @gnakm. I am attaching here for completeness/tracking as she is reviewing. 

Summary of changes: moving the search box, adding a confirmation related to how many items you have selected - shown as zero in mock up - and taking away the "Import to resume builder" words on the button. I think Import is hard for people to understand, even though it's widely used.
The new way puts all the possible actions in a vertical line, by the order that you use them:
view what the translator suggested, then add new ones, then select the final ones. Then you just Finish.
![skills translator - ma changes](https://cloud.githubusercontent.com/assets/17437292/14093477/fb97fa1a-f502-11e5-93e3-d9e3763ac9f7.png)

3) Question for @ayaleloehr The new design would display a count of how many items a user has selected to pull into Resume Builder. This may not possible, depending. Can you please advise?

**Comment by gnakm** [comment]
@mariana-almeida @mollyblake I am not able to open .docx file that you attached to this ticket. Looks like you posted the comment before it full uploaded

**Comment by ayaleloehr** [comment]
Listing the number of skills selected should only be a small lift. 

Adding in the "missing skills" / "Add" button may be simple as well or may be a larger lift. Would have to do a little more diligence on that.

**Comment by mariana-almeida** [comment]
@ayaleloehr That "Missing skills" search box is already in existence. It used to be on the upper right of the skills and it said "Or search manually". So there's no need to develop it. 

Glad to know the number of skills is a "small lift"!

Here's a picture. 
![skills translator - current](https://cloud.githubusercontent.com/assets/17437292/14113297/3722a812-f587-11e5-9810-f82a86f4cdc6.png)

**Comment by mariana-almeida** [comment]
@gnakm - re-attaching the docx with the latest changes. 
[08Jobs_SkillsTranslator_20160328MB.docx](https://github.com/department-of-veterans-affairs/veterans-employment-center/files/193738/08Jobs_SkillsTranslator_20160328MB.docx)

Actually, this is ready for @mollyblake and/or @rcarthur to enter in.

**Comment by ayaleloehr** [comment]
@mariana-almeida well look at that, I "missed" the "missing skills".  :)

**Comment by gnakm** [comment]
Content team @mariana-almeida @rcarthur @mollyblake Is there a way to condense the first two lines? Maybe combine? Combine and trim down? We had a UX issue with the current translator where the results didn't show in the window and users didn't know that they needed to scroll down. I think keep and short and sweet copy on top will help.

Design: @emilyville Thoughts on the new layout? 

![skills translator](https://cloud.githubusercontent.com/assets/13420618/14125803/2da58418-f5db-11e5-99ab-9d275c283d8f.png)

![skills translator result](https://cloud.githubusercontent.com/assets/13420618/14125805/30c93b8a-f5db-11e5-8e55-f5f29b00a9df.png)

**Comment by rcarthur** [comment]
Gina - I think we can just delete the first paragraphs down begin with
"Convert your military experience..."

**Comment by emilyville** [comment]
this looks awesome. Super happy we can condense that top text block, as well! yay @mariana-almeida @gnakm @rcarthur !! If we're all in agreement feel free to assign to me and I will incorporate tomorrow.

**Comment by gnakm** [comment]
I concur with EmDash. 

I tried this. I personally like this route the best because on a large screen, the tips will probably show enough that users don't have to scroll to know what's next. 
![skills translator v 2](https://cloud.githubusercontent.com/assets/13420618/14145301/578846a4-f661-11e5-864c-023f105bfce3.png)
![skills translator result v 2](https://cloud.githubusercontent.com/assets/13420618/14145311/60de7052-f661-11e5-830e-9838e1720997.png)

Assigning it to @emilyville (**soon**) once we're in agreement.

**Comment by rcarthur** [comment]
It looks good!

**Comment by emilyville** [comment]
this is partly mostly
https://github.com/department-of-veterans-affairs/veterans-employment-center/pull/255

**Comment by emilyville** [comment]
I think this is done? I am having trouble following this issue, admittedly my own comment is the most confusing of all... but closing for now and @mariana-almeida please speak up if we missed anything here!

**Comment by mariana-almeida** [comment]
Thanks @emilyville. I've been tracking this issue informally by peering over Gina's shoulder. I'm good.
