### ISSUE TITLE
Remove for_job_seekers page and fix tests

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#247]
The job seekers page needs to be removed from /app/views/static_pages and the tests in job_search_spec.rb will then need to be edited to not `visit for_job_seekers_path` but instead just start on `search_jobs_path`

**Comment by ayaleloehr** [comment]
do this after profile bank deletion, as there will likely be conflicts if we try to do earlier.

**Comment by patrickvinograd** [comment]
This was fixed via #380
