### ISSUE TITLE
Commitment number goes outside of box

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#259]
On our staging commitments page, I put the number of commitments that we have in production, and the last digit goes off the edge of the box:

![screen shot 2016-04-01 at 9 44 38 am](https://cloud.githubusercontent.com/assets/4719765/14208686/95ef7186-f7ee-11e5-9918-ef81c41cf324.png)

**Comment by gnakm** [comment]
@ Would decreasing font size for all 3 boxes be the best way to go about this? Wonder if you have a better solution in mind.

**Comment by emilyville** [comment]
this is done!
