### ISSUE TITLE
New Log In Design

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/veterans-employment-center#274]
@cfeeney-va and I will build out the new employers log in tomorrow. For context we kept it super similar to what we already have because it's prominent. 

![sign in version 1](https://cloud.githubusercontent.com/assets/13420618/14366231/cacd9a5e-fcdf-11e5-887e-0647b92fd01c.png)

![sign in mobile version 1](https://cloud.githubusercontent.com/assets/13420618/14366232/cacec44c-fcdf-11e5-96b8-016437006f89.png)

**Comment by cfeeney-va** [comment]
completed with PR #277
