### ISSUE TITLE
text wrap looks off on C&E page

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#289]
@gnakm is the text in the first 2 sentences on this page supposed to wrap like this?  they both are only going partially across the page.

![screen shot 2016-04-12 at 10 56 26 pm](https://cloud.githubusercontent.com/assets/13770771/14481537/f10fc504-0101-11e6-9b61-6afeafafdf3d.png)

**Comment by gnakm** [comment]
@koconnor719 yes! We standardized all of our texts all throughout vets.gov to a shorter width because it's easier for users to read up to a certain character.

**Comment by ayaleloehr** [comment]
@koconnor719 if you're good with this as a purposeful design decision, please close.

**Comment by emilyville** [comment]
Could we remove this title? I agree it looks odd in this instance and I also question whether it is adding value. @mariana-almeida ?

**Comment by emilyville** [comment]
ok nevermind me, better idea, let's move the title to the top like we normally do :)

![screen shot 2016-05-03 at 5 55 28 am](https://cloud.githubusercontent.com/assets/1307774/14984935/17af9ea2-10fa-11e6-9b1b-86dea5b89196.png)

**Comment by mariana-almeida** [comment]
@emilyville I like the moving of the title up. Looks like it always belonged there!

**Comment by koconnor719** [comment]
ok i think all agreed this is closed?
