### ISSUE TITLE
copy typos on "support for military and veteran spouses"

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#290]
need to capitalize the bullets (connecting with employers...) to match the capitalized bullets on rest of this page. https://www.vets.gov/employment/job-seekers/family-members/ @mariana-almeida is this in our editorial style guide?

![screen shot 2016-04-12 at 10 59 30 pm](https://cloud.githubusercontent.com/assets/13770771/14481588/71b0a8b8-0102-11e6-85d2-2d60a80ed252.png)

**Comment by mariana-almeida** [comment]
@bethpotts to review.

**Comment by bethpotts** [comment]
@koconnor719 @mariana-almeida Our intention was to treat this like a sentence, but you are correct to point out that it looks kinda goofy and would be better to start those two bullets with capital letters. I've made a couple edits, including the capping. Thanks, Kelly! Changes should be reflected on the site by the end of the day.
