### ISSUE TITLE
resume builder not adding skills

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#291]
when i select an unknown MOC and skills (e.g. i selected a bunch of microsoft office skills) they aren't appearing on my resume. (i imported linkedin info to build this resume

[test resume no tranlsated skills.docx](https://github.com/department-of-veterans-affairs/veterans-employment-center/files/216342/test.resume.no.tranlsated.skills.docx)

when i select 11b Army and added microsoft sql and microsoft word, they also don't appear on this resume.
[test resume 2 (11b Army) no .docx](https://github.com/department-of-veterans-affairs/veterans-employment-center/files/216344/test.resume.2.11b.Army.no.docx)

**Comment by ayaleloehr** [comment]
This is a known issue unfortunately. You cannot currently import skills via the skills translator and then use the LinkedIn import. It's a bug, but requires a rework of how we import from LinkedIn, so we don't have an easy resolution path at present.

**Comment by ayaleloehr** [comment]
Actually, @cfeeney-va , are skills even added to resumes currently?  I think they might not be. If not, should they be?

**Comment by cfeeney-va** [comment]
I might not be answering your question (let me know if I'm misunderstanding it!):

Right now, skills are imported from the skill translator if you enter the resume builder from the skills translator page.  However, if you then import from LinkedIn those skills will be overwritten.

**Comment by ayaleloehr** [comment]
Yep, that part makes sense (although obviously isn't ideal and is a bug...).  The part I don't know is whether the skills actually go on the resume? So say I enter 5 skills (from LinkedIn, or manually, or through the skills translator), then I preview and download my resume. Are those skills in the resume?  They seemed to not be showing up for me, so just wanted to check whether that was on purpose or accidental?
