### ISSUE TITLE
job seeker page

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#294]
should these piano keys be on the job seeker page? i don't see any links for Veteran Job seekers to get one-on-one assistance or info on career fairs, etc.? @gnakm 

![screen shot 2016-04-12 at 11 45 22 pm](https://cloud.githubusercontent.com/assets/13770771/14482244/c0a07b82-0108-11e6-90fd-0ca533fb0675.png)

**Comment by mariana-almeida** [comment]
@koconnor719 yes, these are on the page already. Look at #6 for career fairs, and blue box that says: Get personalized help if you need it. Please reopen if I haven't answered your question. Thanks!
