### ISSUE TITLE
MOC issues in Skills Translator

### ISSUE THREAD

**Issue by cfeeney-va** [department-of-veterans-affairs/veterans-employment-center#297]
The Air Force MOS, 1C671, populates the wrong description in the VEC™ profile/resume builder. Once a user enters the MOS in the Skills Translator and imports skills into his/her profile, the description does not match the 1C671 duties/responsibilities.
 
The following Navy NECs--9502, 8427, 8404, 9505, 8424--do not populate a description in the VEC™ profile/resume builder. Once a user enters an MOS in the Skills Translator and imports respective skills into his/her profile, the description of the MOS will also transfer over. However, none of the above Navy NECs populate a description.

**Comment by cfeeney-va** [comment]
@koconnor719 
confirmed with alex that the new MOC data hasn't been imported into the prod database yet; it's waiting on skills translator updates.  all of these issues should be resolved after the import.

**Comment by koconnor719** [comment]
Great. Do we know when skills translator stuff will be done?

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436
