### ISSUE TITLE
employment center subway map

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#300]
given the Veteran feedback we have about the "Interest Profiler" (negative feedback) should that be the #1 step on our subway map--both of these things are external links?  doesn't VA have in-house services  such as http://www.benefits.va.gov/vocrehab/edu_voc_counseling.asp that we can highlight for this step? @rcarthur @mollyblake @gnakm

**Comment by gnakm** [comment]
Closing this because it's a super outdated issue.
