### ISSUE TITLE
VEC Profiles (staging site feedback)

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#328]
@cfeeney-va can you guys pls. review these comments from John and post response below that i can send back to him.

Some of the items I found:
 
Under Employers - If your company’s current job listing is posted on the NLX, then it is also searchable in the Veterans Job Bank. If you haven’t registered your company with the NLX, register now and post for free. Or reach out to qualified Veterans and military spouses directly.  (this link takes them back to the employers page….what is it supposed to connect to?)
 **Link removed**

Under the job posting schema – can you confirm that only verified employers can post this way?
 **This is not currently the case. I will put in an issue for this.  I do not view this as a blocking issue for launch, as we do not verify any of the NLX employers, but do (and will continue to) return results for them, so I don't think showing job results for unverified employers is a major problem**

Under Commitments, it now shows verified employers.  Can we also show the registered employers?
 **No. This was on purpose so that only verified employers show up, making our numbers more accurate and ensuring no inappropriate employer names or commitments show up.**

Under Edit Employer Profile, it states “You must enter your company name, contact information, and EIN before you can start to search.”  Please change to “before you can make a public commitment.”
 **Done**

Also – delete “VA uses your company name and EIN to confirm you are a real company with the IRS. Until approval (which usually takes a few days), you can search Veteran résumés, but you won't be able to see real names or email addresses.”
 **Done**

For the header “Veteran Hiring Commitment (optional)”  Delete (optional) unless they are able to post jobs without being verified.
**Done**

John

**Comment by ayaleloehr** [comment]
@koconnor719 Comments to the individual comments above. Overall, agree with most of these and appreciate the feedback. 

The first one was done and should show up on employment.vets.gov now. 
2 and 3 are not changes that are being made before launch. 
4-6 have a PR out for them. They won't show up in employment.vets.gov yet but I have taken care of all of them and they won't show up on launch. 

Let me know if any of that is unclear!

**Comment by koconnor719** [comment]
email sent with response. closing issue.
