### ISSUE TITLE
Migrations won't run from start

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/veterans-employment-center#344]
Removal of the MigrationHelper module in 24be4ad prevents the migrations from running, since it's referenced in several migrations to assist with loading skills translator models from CSVs:

[`db/migrate/20151014183437_load_skills_translator_model.rb`](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/db/migrate/20151014183437_load_skills_translator_model.rb)
[`db/migrate/20151015183437_create_dummy_skills_translator.rb`](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/db/migrate/20151015183437_create_dummy_skills_translator.rb)
[`db/migrate/20151210212237_add_default_skills.rb`](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/db/migrate/20151210212237_add_default_skills.rb)

This looks like functionality that's available now from the [db:seed_skills task](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/lib/tasks/seed_skills.rake) - should the migrations be consolidated?

**Comment by ayaleloehr** [comment]
@cfeeney-va this was your realm. Thoughts?
