### ISSUE TITLE
Resume editor needs to allow removal of repeat entries.  Can block completion of resume.

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#44]
<a href="https://github.com/jjtswan"><img src="https://avatars.githubusercontent.com/u/12799486?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jjtswan](https://github.com/jjtswan)**
_Tuesday Nov 10, 2015 at 03:15 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/304_

----

OSX Chrome

1. Go to resume builder
2. Get to step 5 (edit profile)
3. Set one location
4. Add another location
5. Oh wait, change your mind and try to remove the 2nd location.  Hm, no button to delete, but let's just set it to blank.
5. Click Preview
6. Generates a page indicating an error: "Location is invalid"

Expected result:
At this point, I should be able to delete the 2nd location altogether so that I can advance.

Actual result:
As is, I cannot advance without filling in a dummy location in my resume.

**Comment by ayaleloehr** [comment]
<a href="https://github.com/ayaleloehr"><img src="https://avatars.githubusercontent.com/u/4719765?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ayaleloehr](https://github.com/ayaleloehr)**
_Wednesday Dec 30, 2015 at 02:41 GMT_

----

A user left feedback (issue 938 in vets-website repo) that this was a problem for them.  That issue should be updated when this is resolved so we can update the user: 

https://github.com/department-of-veterans-affairs/vets-website/issues/938

**Comment by koconnor719** [comment]
to be completed this sprint.

**Comment by cfeeney-va** [comment]
Update: functionality for this is complete and could theoretically be pushed out now.  Manual testing was fine, but I'm having issues implementing automated testing since it has to incorporate jquery responses.  I don't think our codebase currently does that (ex: "Add Experience" functionality does not have tests)

**Comment by koconnor719** [comment]
What is required to complete/ close?
Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by cfeeney-va** [comment]
We should have automated testing for everything we add.  However, right now I've already put a full day of work into trying to get tests to run, so I was going to focus on other tasks for the time being.  This might require a discussion among the group about test coverage.

**Comment by koconnor719** [comment]
Great. Yes, check w/ alex/jeff on our team testing.


Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by cfeeney-va** [comment]
functionality has been written, will most likely go out at the end of this sprint.  needs some additional manual testing that's planned for this week.
