### ISSUE TITLE
Resume editor does not allow addition of repeat skills

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#45]
<a href="https://github.com/jjtswan"><img src="https://avatars.githubusercontent.com/u/12799486?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jjtswan](https://github.com/jjtswan)**
_Tuesday Nov 10, 2015 at 03:17 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/305_

----

OSX Chrome

1. Go to resume builder
2. Try clicking on "Add another skill" under "Your civilian skills"

Actual result:
no change, and JS error "Uncaught ReferenceError: repeatCustomSkill is not defined".

Note that this might be because of a previous JS error:
https://staging.vets.gov/skills-translator/get_common_skills Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ayaleloehr** [comment]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MarinaMartin](https://github.com/MarinaMartin)**
_Monday Dec 21, 2015 at 06:13 GMT_

----

With the "press enter to add" do we actually need the "Add Another Skill" link? @llimllib ?

**Comment by ayaleloehr** [comment]
<a href="https://github.com/llimllib"><img src="https://avatars.githubusercontent.com/u/7150?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [llimllib](https://github.com/llimllib)**
_Monday Dec 21, 2015 at 14:40 GMT_

----

That's a good question. We don't technically need it, so the question is what's the best UI? Will people be messed up by the lack of a button/link to add?

**Comment by ayaleloehr** [comment]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MarinaMartin](https://github.com/MarinaMartin)**
_Tuesday Dec 22, 2015 at 02:37 GMT_

----

Adding design label so UX team can weigh in.

**Comment by ayaleloehr** [comment]
<a href="https://github.com/ayaleloehr"><img src="https://avatars.githubusercontent.com/u/4719765?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ayaleloehr](https://github.com/ayaleloehr)**
_Tuesday Jan 26, 2016 at 20:52 GMT_

----

This is a UX questions. My opinion is that it's fine to keep the "Add another skill" link there (even though pressing enter works as well).  @emilyville if you agree, please close this issue. If you disagree, please assign back to me and I can remove the link.

**Comment by gnakm** [comment]
Anne and I just tested it and we think it's best to get rid of the link, especially since it says (press enter to add). 

Also, could we add a hover over the results? Like the one below.
<img width="280" alt="screen shot 2016-01-28 at 5 29 33 pm" src="https://cloud.githubusercontent.com/assets/13420618/12660976/f1c38eb6-c5e4-11e5-9f54-b3c97b33942a.png">


<img width="207" alt="screen shot 2016-01-28 at 5 30 00 pm" src="https://cloud.githubusercontent.com/assets/13420618/12660968/e1daeed6-c5e4-11e5-8f57-15b902e1c699.png">

**Comment by emilyville** [comment]
sounds good to me! Let's remove the link. Might want to file a separate issue for the hover and label it as an enhancement. 

Just noting: We should streamline how we do dropdowns and default to the right version, and create that  in Roadrunner.
Filed an issue to do that here:
https://github.com/department-of-veterans-affairs/roadrunner/issues/13
