### ISSUE TITLE
Save as draft functionality instructions are confusing.  Doesn't seem to do anything?

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#49]
<a href="https://github.com/jjtswan"><img src="https://avatars.githubusercontent.com/u/12799486?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jjtswan](https://github.com/jjtswan)**
_Tuesday Nov 10, 2015 at 03:42 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/309_

----

Right now, before you go to preview, the user can check a checkbox to "save as draft".  I'm not sure what it's supposed to do... it kind of seems misplaced since the only thing you can do on that page is "preview".

![image](https://cloud.githubusercontent.com/assets/12799486/11053823/8af930fa-8732-11e5-922f-06019440cac3.png)

It also is confusing because it makes me think that there is some immediate action I can directly take on that page that might result in my resume being visible to others.

Maybe it belongs on the next page, where you can "sign in to publicly post your profile".

**Comment by koconnor719** [comment]
this results in a error message.  when i build my resume (using linkedin) then go to bottom of page and try to "save as draft" , i then hit the "preview your veteran profile and resume content button" above and get the following error message.  

![screen shot 2016-02-17 at 9 46 45 pm](https://cloud.githubusercontent.com/assets/13770771/13906347/65e8c200-eeaa-11e5-8a6c-64a5d465fc88.png)

**Comment by ayaleloehr** [comment]
@cfeeney-va  does save as draft really not do anything different?  If so, should we remove it?

**Comment by MarinaMartin** [comment]
Save as draft stops your profile from being in search results.

**Comment by ayaleloehr** [comment]
OK, that seems important. Definitely don't remove it then. The question then becomes can @cfeeney-va  replicate this error that Kelly found?  I wasn't able to when I tried...

**Comment by cfeeney-va** [comment]
I can't replicate the error, but I could see why the current workflow might be confusing.
![screen shot 2016-04-01 at 12 02 05 pm](https://cloud.githubusercontent.com/assets/15927676/14213109/30fdd022-f804-11e5-84c3-0755c680bd3a.png)


I think it would make sense to move it to the next page...maybe something like this?  What do you guys think? (esp @ayaleloehr and @gnakm )

**Comment by koconnor719** [comment]
error message fixed; "saved as draft" is not in scope right now. closed.
