### ISSUE TITLE
Hover State of buttons / rectangles has low contrast

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#55]
<a href="https://github.com/cew821"><img src="https://avatars.githubusercontent.com/u/1237498?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cew821](https://github.com/cew821)**
_Tuesday Nov 10, 2015 at 19:08 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/323_

----

For rectangles with buttons in them, the contrast between button and background is too low.

![image](https://cloud.githubusercontent.com/assets/1237498/11072575/77bc853c-87b4-11e5-87f5-3970c4a2e697.png)

**Comment by gnakm** [comment]
I changed the button color to something we have in our palette but the contrast is still poor.
<img width="782" alt="screen shot 2016-02-05 at 4 09 42 pm" src="https://cloud.githubusercontent.com/assets/13420618/12859278/2356c9cc-cc23-11e5-958b-1f74be3f67d7.png">

What if we made the buttons on the card light grey and have them have linked/ underlined text when hovered over? 
<img width="379" alt="screen shot 2016-02-05 at 4 08 40 pm" src="https://cloud.githubusercontent.com/assets/13420618/12859313/506c10a2-cc23-11e5-98a5-6bcf0b42970a.png">



Btw the samples I mocked up are for another button but same problem.

**Comment by emilyville** [comment]
Wondering - what if instead of buttons we used links in the cards? Occurs
to me a button in a card might be redundant. Then we can list multiples
links, a thing we wouldn't be allowed to do with buttons.

**Comment by gnakm** [comment]
@emilyville Yes! And I foresee more links in cards coming up as we build more content.

Nothing fancy here. Copying GDS's approach
<img width="308" alt="screen shot 2016-02-05 at 7 57 34 pm" src="https://cloud.githubusercontent.com/assets/13420618/12863526/19499096-cc45-11e5-8b0b-b078ad910993.png">


<img width="740" alt="screen shot 2016-02-05 at 8 14 08 pm" src="https://cloud.githubusercontent.com/assets/13420618/12863529/239e3768-cc45-11e5-9b9b-eda13fd373f0.png">

This is an example of having multiple links and hovering over link... just to show that the text hover will be distinct from the other links. Also, this GI Bill button is made up although my choices of the links weren't unintentional...
<img width="725" alt="screen shot 2016-02-05 at 8 14 12 pm" src="https://cloud.githubusercontent.com/assets/13420618/12863535/2de77f18-cc45-11e5-9f81-e7b0939e5a8c.png">

**Comment by emilyville** [comment]
Awesome! Let's do it! It will definitely fix the button color contrast
issue for now.

and we'll sync with @dannychapman on it soon.

**Comment by gnakm** [comment]
Whilst we are still designing a solution for the "link in card/ are these cards or buttons" issue in roadrunner, I was wondering if maybe for this particular issue in VEC, we could just get rid of the "Find Candidate, View Candidate" link. It seems kind of unnecessary to have the card be titled "Your Favorite Veterans" and have a highlighted link to _view_ them. Was there a reason for this link to begin with?
@emilyville @dannychapman

**Comment by emilyville** [comment]
I think you're saying the link in the card is redundant, and we could just have the whole card go to one link? I totally agree. I don't know how we ended up with it as it is (but it was me who added it) beyond "old way" + "new way" = weird combination of ways.
