### ISSUE TITLE
Give some design love to job search results

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#56]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [emilyville](https://github.com/emilyville)**
_Wednesday Dec 02, 2015 at 19:51 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/338_

----

Mostly just design. Maybe remove the icons, but first check the data.

**Comment by gnakm** [comment]
I'm going to close this issue because it is being tackled via issue #93
