### ISSUE TITLE
check on GA integration

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#57]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [emilyville](https://github.com/emilyville)**
_Wednesday Dec 02, 2015 at 20:00 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/341_

----

(Read Noah's instructions)

**Comment by ayaleloehr** [comment]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emilyville](https://github.com/emilyville)**
_Thursday Dec 17, 2015 at 00:39 GMT_

----

I think I wrote "Read Noah's Insructions" while talking to @MarinaMartin, but retained nothing beyond what this says! 

@MarinaMartin - could you send these my way or point me towards them?

**Comment by ayaleloehr** [comment]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emilyville](https://github.com/emilyville)**
_Wednesday Jan 20, 2016 at 16:15 GMT_

----

GA integration will be merged with the new gem

**Comment by koconnor719** [comment]
we closed this during sprint meeting last week?  looks like a number of issues have been reopened that were closed during sprints.  going forward i guess we need to make certain that things are closed?

**Comment by ayaleloehr** [comment]
^^ @plusjeff can you provide some context for why you opened this, what closing criteria will be, and who will own it?

**Comment by plusjeff** [comment]
Think there might have been a hiccup with Waffle
