### ISSUE TITLE
Location for job bank search

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#60]
<a href="https://github.com/cfeeney-va"><img src="https://avatars.githubusercontent.com/u/15927676?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cfeeney-va](https://github.com/cfeeney-va)**
_Friday Dec 04, 2015 at 22:11 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/357_

----

The "Advanced search" for the job bank lets the user put in both a City/State and Zip Code and doesn't enforce that they match.  It also doesnt seem to be using the zip code for the search (whether the other field is entered or not).

**Comment by ayaleloehr** [comment]
<a href="https://github.com/ayaleloehr"><img src="https://avatars.githubusercontent.com/u/4719765?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ayaleloehr](https://github.com/ayaleloehr)**
_Tuesday Jan 26, 2016 at 21:06 GMT_

----

Zip code doesn't seem to be working at all. We should either make it work or remove it.

**Comment by ayaleloehr** [comment]
@cfeeney-va it seems when I do a search with a zip code entered, it removes the zip code after the search is performed (and the zip code isn't used in the search). I'm thinking we should just remove the Zip Code + Distance fields in this, as we already have the "Where" field. Thoughts?

**Comment by cfeeney-va** [comment]
I agree...when I looked at it we weren't using the zip code anywhere and we would have to do a lot of work to integrate it.  Since we already have a location field I think removing it is the way to go.

**Comment by ayaleloehr** [comment]
Thanks. On it!
