### ISSUE TITLE
Commitment page form needs more validation, takes negative / numeric

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#64]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [emilyville](https://github.com/emilyville)**
_Wednesday Dec 09, 2015 at 01:28 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/367_

----

![screenshot from 2015-12-04 15-45-42](https://cloud.githubusercontent.com/assets/1307774/11673863/0558db0c-9dea-11e5-94d7-7c1c448726e0.png)

via @paultag (thanks!)

**Comment by ayaleloehr** [comment]
@cfeeney-va pretty sure you got this one. can you verify and if so, close?

**Comment by cfeeney-va** [comment]
Yup, this should be fixed :)
Tried -28, 12.5, and 1,000 (with comma) and all were caught by current validations

**Comment by ayaleloehr** [comment]
:)
