### ISSUE TITLE
Add coursera logo to coursera box

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#65]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [emilyville](https://github.com/emilyville)**
_Wednesday Dec 09, 2015 at 02:20 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/368_

----

like linkedin!

**Comment by gnakm** [comment]
Rosye approved the removal of all logos. 
Now Issue #178
