### ISSUE TITLE
Transfer LinkedIn and Google app keys

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#73]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MarinaMartin](https://github.com/MarinaMartin)**
_Wednesday Dec 09, 2015 at 22:38 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/392_

----

I am working on this with Greg. Update callback URLs to new vets.gov environment.

**Comment by ayaleloehr** [comment]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MarinaMartin](https://github.com/MarinaMartin)**
_Tuesday Dec 22, 2015 at 02:19 GMT_

----

We are still waiting on LinkedIn to enable r_fullprofile, once they do that we can switch key.

**Comment by ayaleloehr** [comment]
I think this has been done but will confirm this sprint.

**Comment by MarinaMartin** [comment]
This has not because LinkedIn took forever updating the rProfile for the new one. We can do it now though!

**Comment by MarinaMartin** [comment]
This is not done. Why was it closed?

**Comment by koconnor719** [comment]
we closed it in our sprint planning meeting; team confirmed it was done.

**Comment by ayaleloehr** [comment]
Conversation with Marina now confirms we can close this.
