### ISSUE TITLE
test on moar browsers

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#76]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [emilyville](https://github.com/emilyville)**
_Friday Dec 11, 2015 at 15:56 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/416_

----

None

**Comment by koconnor719** [comment]
complete = look in IE10

**Comment by MarinaMartin** [comment]
@emilyville Will Roadrunner have a browser testing feature like Sauce Labs?

**Comment by koconnor719** [comment]
gina needs to get a tool for this (talk to emdash)

**Comment by koconnor719** [comment]
this should be tied to deployment; need this as a repeating task in operations.

**Comment by koconnor719** [comment]
gina will test out browsers this sprint and then we'll close.

**Comment by koconnor719** [comment]
every sprint.
