### ISSUE TITLE
a few 508 issues on the resume builder

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#77]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [emilyville](https://github.com/emilyville)**
_Thursday Dec 17, 2015 at 02:14 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/425_

----

mostly just labels not correlating with fields - I think there are about 4

**Comment by ayaleloehr** [comment]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MarinaMartin](https://github.com/MarinaMartin)**
_Sunday Dec 20, 2015 at 23:19 GMT_

----

@emilyville Is there a list of the issues? How can we re-create?

**Comment by koconnor719** [comment]
now have the 508 office checkin this for us
