### ISSUE TITLE
Trashcan icon does not appear in IE

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#81]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MarinaMartin](https://github.com/MarinaMartin)**
_Tuesday Dec 22, 2015 at 01:22 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/450_

----

The trashcan icon to delete a skill within the resume creation page does not appear in Internet Explorer (I think 11).

**Comment by cfeeney-va** [comment]
Trashcan icon appears and works to delete skills when I checked in IE11 (under "Your Civilian Skills").  Do we have any more info on this?

**Comment by ayaleloehr** [comment]
@MarinaMartin do you know the origin of this issue?  My thought is we close it since we cannot reproduce.

**Comment by MarinaMartin** [comment]
When I log into vec from a Windows machine at VA I do not see the trashcan

**Comment by cfeeney-va** [comment]
Verified that I also don't see the trashcan when on the VA network.  Icon exists on the page and works, but there is no picture (aka it looks like you're clicking on nothing but the skill will be deleted)

**Comment by emilyville** [comment]
OHHH! this is likely the VA network icon issue. pinging @rickleegit and @plusjeff since I think they've encountered before.

**Comment by rickleegit** [comment]
We were never able to resolve this for CT. We tried Jeff's fix. No joy. :-(

**Comment by cfeeney-va** [comment]
Thanks @emilyville and @rickleegit!  @plusjeff, do you guys know what the underlying issue is?

**Comment by plusjeff** [comment]
Nope. Sorry! I believe what I tried was forcing IE into Edge mode (maybe?) That involved putting this line at the top of the file to ensure it's rendered in the latest rendering engine available to IE:

`<meta http-equiv="X-UA-Compatible" content="IE=edge">`

The VA automatically forces pages to render in IE7 mode, but this overrides that and forces a newer renderer to run. But alas, don't think it worked for this particular problem.

**Comment by rickleegit** [comment]
svgs might work?

**Comment by emilyville** [comment]
Are we totally stuck on an icon? Making icons work at the VA is a frustrating problem (because it's not veteran facing)

I suggest... 
in css add something like 
`content: "delete"`
that shows up in lieu of the icon. 

And if that's too buggy, just remove the icon completely and have it say "delete". 

@gnakm or @dannychapman or @akainic might also have ideas!

**Comment by rickleegit** [comment]
"Making icons work at the VA is a frustrating problem (because it's not
veteran facing)" - yeah it is. I punted on it for the time being on CT.

Is it worth looking at a solution for future apps? Probably less of an
issue for the content heavy pages, though.

**Comment by emilyville** [comment]
I think the solution in general has been to use icons not at all or very sparingly (and where they supplement existing content - so if they aren't there no functionality is lost)

but we haven't been diligent about this - and we have exceptions.

**Comment by dannychapman** [comment]
I'd also try to avoid icon fonts from an accessibility perspective. That said, SVG, or plain old icon sprits would be tenable when we do have an exception. In general though, I think the threshold should be fairly high in terms of not using icons by default.

**Comment by akainic** [comment]
I like @emilyville's backup solution of using before or after content! Is that possible to do conditionally?
