### ISSUE TITLE
Search button on Veteran search is oddly small

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#82]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MarinaMartin](https://github.com/MarinaMartin)**
_Tuesday Dec 22, 2015 at 05:16 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/458_

----

![image](https://cloud.githubusercontent.com/assets/489465/11948362/38b19e10-a841-11e5-8091-e5f149edd604.png)

**Comment by koconnor719** [comment]
anne fixed buttons in other places; will confirm fixed here.

**Comment by akainic** [comment]
The fix I made (which has been merged, but not yet deployed), changed the proportions of the button, but does not make it longer. It will look like this once deployed:

<img width="1038" alt="screenshot 2016-02-18 16 31 15" src="https://cloud.githubusercontent.com/assets/3886085/13158905/1e24f750-d65d-11e5-87f5-bc857ccb44e4.png">

If we want the button to be longer, we can definitely do that, but I think that will require a new PR.

**Comment by akainic** [comment]
Here is the fix I made: https://github.com/department-of-veterans-affairs/veterans-employment-center/pull/140/files#diff-2617b370d37c86f9ce523807fb8bc9faR429

@koconnor719 Let me know if you need any other info!
