### ISSUE TITLE
Remove ALP search field

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#84]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MarinaMartin](https://github.com/MarinaMartin)**
_Tuesday Dec 22, 2015 at 05:17 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/460_

----

No longer needed.

![image](https://cloud.githubusercontent.com/assets/489465/11948380/73683ff0-a841-11e5-9834-e527983367e6.png)

**Comment by cfeeney-va** [comment]
Update: completed, pending pull request
