### ISSUE TITLE
Make it easier for admins to approve employers

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#89]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MarinaMartin](https://github.com/MarinaMartin)**
_Wednesday Dec 23, 2015 at 04:44 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/472_

----

If an employer doesn't fill out their info to be approved until after they create their account, the admins don't necessarily see it at the top of the list. We should make this process easier for them.

This could use a usability test so we better understand their workflow.

This is high priority.

**Comment by ayaleloehr** [comment]
<a href="https://github.com/ayaleloehr"><img src="https://avatars.githubusercontent.com/u/4719765?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ayaleloehr](https://github.com/ayaleloehr)**
_Thursday Jan 07, 2016 at 13:49 GMT_

----

@maryannbrody this is something you and I should tackle. Let's discuss in person this week and find some time to go meet with the VA admins up on the 8th floor?

**Comment by koconnor719** [comment]
mary ann to get w/ john thompson and robert sanders

**Comment by maryannbrody** [comment]
@ayaleloehr Can you please make the intro/schedule something for this? I think it'd be good to do 1 on 1's with each stakeholder (so 2 separate meetings) -- Wednesday and Friday AM look good this week.

**Comment by gnakm** [comment]
I am going to close this because we had our usability testings with John Thompson and Robert Sanders on Friday 2/5 and our new findings have been broken down into issues.
