### ISSUE TITLE
Create new mockup of Job Seeker landing page

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#90]
<a href="https://github.com/maryannbrody"><img src="https://avatars.githubusercontent.com/u/12674895?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maryannbrody](https://github.com/maryannbrody)**
_Wednesday Dec 23, 2015 at 20:37 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/474_

----

From usability testing... 

Participants were not sure where to start on this page. 

Participants were not sure how to start their job search "I don't even know what to type into the box."

From team discussion: What if we moved the skills translator up ? And what if the job search feature was a call to action button linking to a secondary page? What if we allowed users to browse by industry instead of searching blindly? Overall this page needs to support users in accomplishing their goals of 1) finding out what they're qualified for and 2) browsing to see what might be an option for them.

**Comment by ayaleloehr** [comment]
<a href="https://github.com/maryannbrody"><img src="https://avatars.githubusercontent.com/u/12674895?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maryannbrody](https://github.com/maryannbrody)**
_Wednesday Dec 23, 2015 at 20:40 GMT_

----

Note: If we're looking at search and considering offering more of a browse experience, we discussed looking at search term analytics to determine where to start.

**Comment by gnakm** [comment]
![artboard 1](https://cloud.githubusercontent.com/assets/13420618/13359150/ad3b488a-dc80-11e5-8428-363b32235fa2.png)

![artboard 2](https://cloud.githubusercontent.com/assets/13420618/13359154/af0b1a28-dc80-11e5-9da5-6b5a95b086da.png)

**Comment by koconnor719** [comment]
this sprint: complete

**Comment by emilyville** [comment]
The copy

(matches the copy) then

Three main options/cards: 
1. Skills Translator
2. Resume Builder
3. Job search 

After that...
Linkedin/Coursera

**Comment by gnakm** [comment]
@emilyville 

Would it be weird to have the LinkedIn/ Coursera sections in piano keys? 
![side](https://cloud.githubusercontent.com/assets/13420618/13643476/180c9d4a-e5ef-11e5-8be2-92d57ffc5ac9.png)

I made a side nav version. This in general is up for a bigger discussion around navigation. 
![piano keys](https://cloud.githubusercontent.com/assets/13420618/13643487/28891f9a-e5ef-11e5-8ff0-af983f2991b4.png)

**Comment by emilyville** [comment]
Awesome! I'll add this page to the jekyll site - and from there comment back. 

We chatted and decided to keep the coursera and linkedin as grey boxes - but put them underneath the blue three, for now.

**Comment by emilyville** [comment]
So just updating after on some IA surgery, this page (new mockup) with be the Veteran Employment Center landing page for job seekers. It will still live in the jekyll site, so no change needs to happen to this actual page - but I will make a new one. Once that one is in the new branch for deployment I'll close this issue.

**Comment by emilyville** [comment]
here is the new page (still needs some descriptions). closing this now! @gnakm or @mariana-almeida feel free to comment with thoughts or ideas :)

![screencapture-0-0-0-0-4000-employment-job-seekers-veterans-employment-center-1457580844597](https://cloud.githubusercontent.com/assets/1307774/13658674/09130baa-e62e-11e5-8387-c41894929186.png)
