### ISSUE TITLE
Mockup job search results page with the following changes...

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#93]
<a href="https://github.com/maryannbrody"><img src="https://avatars.githubusercontent.com/u/12674895?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maryannbrody](https://github.com/maryannbrody)**
_Wednesday Dec 23, 2015 at 21:07 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/477_

----

(From usability testing..)

1. Slim job search boxes above the search results so that results will display above the fold (consider collapsing MOS into advanced search on this page, and moving the "Search" button up in it's place. See indeed: http://www.indeed.com/jobs?q=plumber&l=Washington)

2. Add "Showing x of y results" to the mockup (above featured jobs). 

3. Adjust and minimize social media buttons. Indefinitely remove Delicious and Pinterest. Suggestion: Make the remaining buttons about 50% of the size, with a label above each set that says "Share this job."

3A. ALTERNATIVE solution for social media buttons -- we could have one button "Share this job." When you click on the button, a drawer opens and you can click how you want to Share it. We can do this easily with Share This APIs.

**Comment by ayaleloehr** [comment]
<a href="https://github.com/gnakm"><img src="https://avatars.githubusercontent.com/u/13420618?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gnakm](https://github.com/gnakm)**
_Tuesday Jan 26, 2016 at 23:24 GMT_

----

If we decide to use social media buttons, we should keep them around 24 x 24px
Also, having "job posted" result on 2nd line will make it easier for users to reach and navigate

![collapsed](https://cloud.githubusercontent.com/assets/13420618/12598705/e8242712-c459-11e5-95da-8301049ca4c3.png)

![show](https://cloud.githubusercontent.com/assets/13420618/12598707/ed0a59cc-c459-11e5-934d-238b1df264da.png)

**Comment by ayaleloehr** [comment]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MarinaMartin](https://github.com/MarinaMartin)**
_Tuesday Jan 26, 2016 at 23:27 GMT_

----

I think we have good data that no one uses the social media buttons.

**Comment by ayaleloehr** [comment]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emilyville](https://github.com/emilyville)**
_Tuesday Jan 26, 2016 at 23:29 GMT_

----

Nice, Gina!

I'd be pretty excited to remove them completely - last I heard that was a
non starter? But maybe it's a brave new world now and we should go for it!

**Comment by ayaleloehr** [comment]
<a href="https://github.com/maryannbrody"><img src="https://avatars.githubusercontent.com/u/12674895?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maryannbrody](https://github.com/maryannbrody)**
_Wednesday Jan 27, 2016 at 02:49 GMT_

----

Hey, @gnakm! Thanks for sharing and it's super awesome to start to see some usability findings being implemented. 

I wanted to send you some feedback:
- I'd echo marina & emily that we can probably just get rid of the social media buttons. The only one I'm thinking about keeping is the "email" feature. What if we kept it as a link, below the job posting like this: 
![image](https://cloud.githubusercontent.com/assets/12674895/12602089/83c95cf4-c474-11e5-848e-d2d53930e097.png)
- Let's break the site's link color convention and go with something more traditional for this page to make it easier to scan. (OK with you @emilyville?). See: https://playbook.cio.gov/designstandards/visual-style/#links
- I like that you moved the "job posted" date to facilitate scanning. Let's take it a step further and make it super easy to scan by making each postings 3 or 4 lines depending on if you include the "email link" [Job Title // Company, City, State // Job Posted Date // Email this job (?) ]. 
- Please add "Jobs 1 to 10 of 240" to the mockup


Let me know if you have questions!!! (Or if anyone else wants to chime in.)

Thanks, 
Mary Ann

**Comment by MarinaMartin** [comment]
I have data on the social media buttons. In the last 90 days of VEC in eBenefits, a social media save button was clicked 339 times (0.29% of people looking at the job search results). That data implies removing them to me.

**Comment by gnakm** [comment]
@maryannbrody, @emilyville 
Could you guys please take a look at this edit? Thanks!

![job seeker search](https://cloud.githubusercontent.com/assets/13420618/12721463/f4d84ba0-c8cd-11e5-89d2-f6c9a256eafe.png)

**Comment by gnakm** [comment]
Actually, I prefer it with the links in our Primary Darker (Hex value: #205493)
It looks slightly more refined than the lighter blue. 

![collapsed copy](https://cloud.githubusercontent.com/assets/13420618/12731956/4ae46c26-c901-11e5-8667-23b4f206ee11.png)

**Comment by maryannbrody** [comment]
Hi, @gnakm -- i think this is an awesome improvement over what we currently have. Woohoo!

Per @MarinaMartin's comment about analytics of social/share buttons, let's just get rid of the email functionality altogether. 

Otherwise this looks good to me! Let's get this over to Anne  unless there's additional feedback from @emilyville

**Comment by koconnor719** [comment]
@gnakm do we want to get some time from Rosye this week to go over these design items (social media buttons, warning language about job scams, etc.) do we want to try and run a few items by her on wed if we have time--the ones we want to do right away?  then maybe set up a follow up design review session for any other items you have on your list??

**Comment by emilyville** [comment]
Do we need to show Rosye iterative design improvements that don't
significantly effect functionality? I'd propose we just keep in shipping
and change course of that becomes a problem.

We can always reinstate old versions if we have to....

Looks good @gnkm! Let's stick with whatever link color is baked in - unless
we make that a global change.

**Comment by MarinaMartin** [comment]
I would vote for showing the stakeholder a new design ahead of time but not waiting on them for approval, as a best practice. It's not fun to learn about a change on stage or when giving a demo and seeing a new design, etc

**Comment by emilyville** [comment]
Good point. You guys know them better than I do! I just think ..

1) designs are almost always worse when done by committee
2) people have a hard time seeing design changes and not weighing in on
things they normally wouldn't even notice!

I don't think we're doing either of these things now. So I'm just being
cautionary.

**Comment by maryannbrody** [comment]
I agree with @emilyville and @MarinaMartin - definitely a balancing act between being inclusive and moving forward. 

When we share with stakeholders, I suggest that we always root it in a usability findings/data. (The user knows best.)

So in this example, the key messages are: "We made some improvements based on observing veterans use the tool. When we watched users search for a job, a few users didn't realize anything had changed on the page when they hit search because the results were below the fold. We also noticed that they had difficulty scanning the results and didn't use the social media sharing buttons (also didn't know what some of them even were). Analytics data also shows that these are never clicked ("email was clicked 0.29% of users on the page clicked "email", for example).... etc."

I'm happy to help with this framing.

**Comment by gnakm** [comment]
@emilyville The current links are the grey linked text on grey, so keep as it is, correct? I also took out the email. 
<img width="758" alt="screen shot 2016-02-02 at 11 54 14 am" src="https://cloud.githubusercontent.com/assets/13420618/12756843/8bb9936e-c9a3-11e5-8d5e-4d7b99808069.png">

If we all agree on showing the new design (which I, too, am raising my hand for), I am going to pass this to Anne.

**Comment by emilyville** [comment]
Looks great! Let's add another link style soon, but in a different change
and we'll loop in @dannychapman
