### ISSUE TITLE
Add link to VEC

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#97]
<a href="https://github.com/koconnor719"><img src="https://avatars.githubusercontent.com/u/13770771?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [koconnor719](https://github.com/koconnor719)**
_Thursday Jan 07, 2016 at 18:14 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/487_

----

Add a link to VEC for this blog post from LaVerne with a proposed heading, "Make sure you know how to protect yourself!": http://www.blogs.va.gov/VAntage/23299/veterans-employment-center-website-false-claim-of-breach/  to VEC page as a precaution / proactive information for Veterans.  note: there is no issue on VEC, but this is helpful information in general for users. 

@MarinaMartin

**Comment by ayaleloehr** [comment]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emilyville](https://github.com/emilyville)**
_Thursday Jan 07, 2016 at 18:41 GMT_

----

We don't really have a place we add links to temp. stuff like blog posts (yet?). Did you have a spot in mind for this to go @koconnor719 ?

**Comment by ayaleloehr** [comment]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MarinaMartin](https://github.com/MarinaMartin)**
_Thursday Jan 07, 2016 at 18:44 GMT_

----

I think we want less of a "link to a blog post" and more of a "Make sure you know how to protect yourself!"

**Comment by ayaleloehr** [comment]
<a href="https://github.com/koconnor719"><img src="https://avatars.githubusercontent.com/u/13770771?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [koconnor719](https://github.com/koconnor719)**
_Thursday Jan 07, 2016 at 18:51 GMT_

----

could we add a link on the job seeker page under the steps to finding a job?  maybe not a step--but a note below that with the link?  

<img width="710" alt="screen shot 2016-01-07 at 1 50 58 pm" src="https://cloud.githubusercontent.com/assets/13770771/12179602/ccdfd398-b545-11e5-81af-4d876d43e3ed.png">

**Comment by ayaleloehr** [comment]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emilyville](https://github.com/emilyville)**
_Friday Jan 08, 2016 at 15:41 GMT_

----

OK. So rather than thinking about this as adding a link to a blog post, we need to add some content with a notice about job scams - that sends you to this post for more information. Would that work?

I'll pow-wow with Ric and we can propose a solution here.

**Comment by ayaleloehr** [comment]
<a href="https://github.com/koconnor719"><img src="https://avatars.githubusercontent.com/u/13770771?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [koconnor719](https://github.com/koconnor719)**
_Friday Jan 08, 2016 at 15:42 GMT_

----

Sounds good
Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by ayaleloehr** [comment]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emilyville](https://github.com/emilyville)**
_Friday Jan 08, 2016 at 18:13 GMT_

----

tagging the user voice issue for context: https://github.com/department-of-veterans-affairs/vets-website/issues/996

**Comment by ayaleloehr** [comment]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MarinaMartin](https://github.com/MarinaMartin)**
_Sunday Jan 10, 2016 at 22:12 GMT_

----

I don't think we should include a link that says "breach" in the name... that seems unnecessarily alarming. Instead we should link to something that can help Veterans identify and protect against phishing, broadly, which is important.

**Comment by ayaleloehr** [comment]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emilyville](https://github.com/emilyville)**
_Monday Jan 11, 2016 at 01:04 GMT_

----

It seems like the right time to mention this is when you give us your email, or create a profile. Basically whatever moment you are making yourself eligible for employers to reach out to you. 

We could then outline some steps for how to protect yourself, basically what @MarinaMartin just said. I have time set up to walk through this with @rcarthur this week!

**Comment by ayaleloehr** [comment]
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emilyville](https://github.com/emilyville)**
_Wednesday Jan 20, 2016 at 16:26 GMT_

----

have a snippet from  Ric to add - Just need to add it.

**Comment by emilyville** [comment]
Here is the new copy!

FRAUD WARNING: Fraudulent attempts have been made to collect user information by accessing Veteran profiles on the VEC website. Please know that VA will not ask for your personal information via email and that VEC does not store résumés or other personally identifying information. If you believe you were targeted by a potential online scam for jobs or otherwise, please contact the appropriate authorities. For more information on this, and to find out what to do if you are approached or are a victim of fraud, take a look at (this blog)[http://www.blogs.va.gov/VAntage/23299/veterans-employment-center-website-false-claim-of-breach/].

**Comment by emilyville** [comment]
@MarinaMartin raised an excellent point that we should approve this language. @koconnor719 - assigning to you to run this by Rosye.

**Comment by emilyville** [comment]
@gnakm - if you have a moment and you can find a good spot where this warning should go, that might help with approval! I'm thinking we want to put it somewhere on the resume-saving page, in the least ostentatious way possible, either in a modal or at the bottom of the page.

**Comment by koconnor719** [comment]
Or maybe on the job seeker page?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by gnakm** [comment]
I think it will be best on the resume-saving page, right before the user submits to preview his/her profile. I think the job seeker page is a little more general and users don't have to insert any personal information, so they may be more likely to miss the note. The blue modular box may be better than text alone because it's a friendly color yet still stands out from all of the other texts on the page. @emilyville Is it ostentatious?

![fraud warning modular](https://cloud.githubusercontent.com/assets/13420618/12727645/d84e5b78-c8eb-11e5-866c-6875cf8443b0.png)
![fraud warning](https://cloud.githubusercontent.com/assets/13420618/12727646/d8522870-c8eb-11e5-8818-8fcf8a2283ff.png)

**Comment by koconnor719** [comment]
@gnakm we are trying to set up a meeting w/ rosye this week--i'll include you and we can have her take a quick look at this and approve:)  we need to get her approval on the language first fyi.  thx. this looks great!

**Comment by gnakm** [comment]
We got the copy approved by Rosye today: 

**Protect Yourself**: Job seekers often find themselves targets of phishing scams. Please know that VA does not ask for your personal information or financial information via email. If you get an email from an employer asking for your personal or financial information, please be cautious.  For more information on this, and to find out what to do if you are approached or are a victim of phishing, take a look at [this blog](http://www.blogs.va.gov/VAntage/23299/veterans-employment-center-website-false-claim-of-breach/).

![fraud warning modular v 2](https://cloud.githubusercontent.com/assets/13420618/12926002/3a067fbe-cf2f-11e5-8d8e-7040bc2b6909.png)

passing this to @akainic now.
